name: whatthehack
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.2
  shared_preferences: '0.5.10'
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_progress_button: ^1.0.0
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.2
  syncfusion_flutter_charts: ^18.2.57
  syncfusion_flutter_gauges: ^18.2.57
  flutter_icons: ^1.1.0
  form_bloc:
  flutter_form_bloc:
  flutter_bloc:
  expandable: ^4.1.4
  flutter_map:
    git:
      url: https://github.com/maRci002/flutter_map.git
  latlong: ^0.6.1
  global_configuration: ^1.6.0
  flare_flutter: ^2.0.6
  animated_text_kit: ^2.2.0
  flutter_contact: ^0.6.1
  beauty_textfield:
    git:
      url: https://github.com/hipoojan/BeautyTextfield.git
  camera: ^0.5.8+6
  video_player: ^0.10.12+3
  speech_to_text: ^2.6.0
  url_launcher: ^5.6.0
  geolocator: ^6.0.0
  flutter_form_builder: ^3.13.5
  model_renderer:
    path: ../model_renderer




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "DriveSafe"





flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/cfg/
    - assets/testmap.png
    - assets/mooodel.jpg
    - assets/login.flr
    - assets/login6.flr

  fonts:
    - family: Spartan
      fonts:
        - asset: fonts/Spartan-Regular.ttf
        - asset: fonts/Spartan-Light.ttf
          weight: 300
        - asset: fonts/Spartan-Medium.ttf
          weight: 500
        - asset: fonts/Spartan-SemiBold.ttf
          weight: 600

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
